/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER SWIFT 1
 */
import javax.swing.JOptionPane;
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuFileExit = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUtilityHitungLingkaran = new javax.swing.JMenuItem();
        menuUtilityTransaksi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jButton1.setText("jButton1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFile.setText("File");

        jMenuItem1.setText("Exit");
        menuFile.add(jMenuItem1);

        menuFileExit.add(menuFile);

        jMenu2.setText("Utility");

        menuUtilityHitungLingkaran.setText("HitungLingkaran");
        menuUtilityHitungLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilityHitungLingkaranActionPerformed(evt);
            }
        });
        jMenu2.add(menuUtilityHitungLingkaran);

        menuUtilityTransaksi.setText("Transaksi");
        menuUtilityTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilityTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuUtilityTransaksi);

        menuFileExit.add(jMenu2);

        jMenu1.setText("Help");

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemAbout);

        menuFileExit.add(jMenu1);

        setJMenuBar(menuFileExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        JOptionPane.showMessageDialog(
        this,
        "Program ini dibuat oleh Keysa Anargya Putri"
    );
    
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuUtilityHitungLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilityHitungLingkaranActionPerformed
       FormLingkaran f = new FormLingkaran();
    f.setVisible(true);
    }//GEN-LAST:event_menuUtilityHitungLingkaranActionPerformed

    private void menuUtilityTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilityTransaksiActionPerformed
        new FormTransaksi () .setVisible(true);
    }//GEN-LAST:event_menuUtilityTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuBar menuFileExit;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuUtilityHitungLingkaran;
    private javax.swing.JMenuItem menuUtilityTransaksi;
    // End of variables declaration//GEN-END:variables
}
